name: redgate-subset-image-example
 
schedules:
- cron: 0 3 * * * # cron syntax for 3am daily
  branches:
    include: 
    - main
  displayName: 3am daily # friendly name given to a specific schedule

trigger: none

parameters:
- name: serverinstance
  default: "WIN2016"
- name: databaseName
  default: "Northwind"
- name: backupDir
  default: 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Backup'

stages:
  - stage: Subset  
    displayName: Subset
    jobs:
    - job: ${{parameters.databaseName}}
      displayName: Subset ${{parameters.databaseName}}

      steps:
      - powershell: |
          $backupDir = "${{parameters.backupDir}}"
          $databaseName = "${{parameters.databaseName}}"
          $mostRecentBackup = (Get-ChildItem -Path $backupDir | Where-Object {$_.Name -like "*$databaseName*"} | Sort-Object -Descending -Property LastWriteTime)[0]
          $backupPath = "${backupDir}\$mostRecentBackup"
          Write-Output "Most recent backup for $databaseName is: $backupPath"

          import-module dbatools
          Restore-DbaDatabase -SqlInstance ${{parameters.serverinstance}} -Path "$backupPath" -DatabaseName "${{parameters.databaseName}}_FullRestore" -DestinationFileSuffix "_FullRestore"
        displayName: 'Restore backup'
      - powershell: |
          # Create a DBCC clone of the source DB
          $sourceDb = "${{parameters.databaseName}}_FullRestore"
          $targetDb = "${{parameters.databaseName}}_Subset"
          $sql = "DBCC CLONEDATABASE ( $sourceDb , $targetDb ); ALTER DATABASE $targetDb SET READ_WRITE WITH ROLLBACK IMMEDIATE;"

          import-module dbatools
          Invoke-DbaQuery -SqlInstance ${{parameters.serverinstance}} -Query $sql
        displayName: 'Create target for subset'
      - powershell: |
          # params in
          $serverinstance = "${{parameters.serverinstance}}"
          $sourceDb = "${{parameters.databaseName}}_FullRestore"
          $targetDb = "${{parameters.databaseName}}_Subset" 
          
          # params out
          $sourceConnectionString = "server=${serverinstance};database=${sourceDb};Integrated Security=true;TrustServerCertificate=true"
          $targetConnectionString = "server=${serverinstance};database=${targetDb};Integrated Security=true;TrustServerCertificate=true"
          $startingTable = "dbo.Orders"
          $filterClause = "OrderId < 10260"

          # running subset
          subsetter --database-engine=sqlserver --source-connection-string=$sourceConnectionString --target-connection-string=$targetConnectionString --starting-table=$startingTable --filter-clause=$filterClause
        displayName: 'Run subset'
      - powershell: |
          $subsetDb = "${{parameters.databaseName}}_Subset"
          
          import-module dbatools
          Backup-DbaDatabase -SqlInstance ${{ parameters.serverinstance }} -Database $subsetDb
        displayName: 'Backup target'
      - powershell: |
          # Delete both staging databases
          $sourceDb = "${{parameters.databaseName}}_FullRestore"
          $subsetDb = "${{parameters.databaseName}}_Subset"
          $sql = "DROP Database $sourceDb; DROP Database $subsetDb;"
          import-module dbatools
          Invoke-DbaQuery -SqlInstance ${{parameters.serverinstance}} -Query $sql
        displayName: 'Clean up'
      - powershell: |
          Write-Output "To do: Copy backup to fileshare"
        displayName: 'Copy backup to file share'